### PR TITLE
D8CORE-4802 D8CORE-4823

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Updating to the new Decanter.
   -  https://github.com/SU-SWS/decanter/compare/6.2.1...6.2.5 - The differences.
   - Getting the new colors.
   - fixing the Discrimination link so it goes to: https://bulletin.stanford.edu/pages/c7vDgeOuJIfpZe8GKmW3/
   - Set up work to put the mail to external link icons in front.

# Review By (Date)
- 11/5

# Criticality
- Normal

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to the homepage and verify the Discrimination link has changed to:  https://bulletin.stanford.edu/pages/c7vDgeOuJIfpZe8GKmW3/
4. Verify no other visible changes.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Stanford Basic Theme
- SOE Basic
- SAA Victoria
- VPUE
- Jumpstart_ui
- stanford_starter

# Associated Issues and/or People
- [D8CORE-4802](https://stanfordits.atlassian.net/browse/D8CORE-4802)
- [D8CORE-4802](https://stanfordits.atlassian.net/browse/D8CORE-4802)
- https://github.com/SU-SWS/stanford_basic/pull/249
- https://github.com/SU-SWS/stanford_starter/pull/16
- https://github.com/SU-SWS/vpue_undergrad_subtheme/pull/36
- https://github.com/SU-SWS/saa_victoria_subtheme/pull/205
- https://github.com/SU-SOE/soe_basic/pull/87
- https://github.com/SU-SWS/jumpstart_ui/pull/117
- @cjwest @jdwjdwjdw @rebeccahongsf 

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by cjwest** [comment]
@jenbreese ,
Thank you for doing this!

I'm wondering, are we running visual regression testing for this?

**Comment by jenbreese** [comment]
> @jenbreese , Thank you for doing this!
> 
> I'm wondering, are we running visual regression testing for this?

@cjwest Yes, we would do the regular visual regression I think.

**Comment by rebeccahongsf** [comment]
Thanks for putting this PR together @jenbreese :) I'll test out this branch locally and on the [Associates test site](https://saaassociates-test.sites.stanford.edu/) and do a diffy comparison to prod.

**Review by rebeccahongsf — APPROVED** [review]
Looks good to me locally and diffy returns no differences 😎

**Pull request merged**
