### PR TITLE
adapt-1199-icon-header-spacing: reducing heading spacing on an icon card

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Reducing the spacing on the icon heading card with an image.

# Review By (Date)
- 3/26

# Criticality
- Low

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Clear caches.
3. View an icon card and see the spacing above the icon is less. 
4. Verify the icon card without an icon is also matching the spacing.
Screen Shot 2021-03-24 at 3 14 43 PM
Screen Shot 2021-03-24 at 3 02 31 PM

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- SAA Subtheme

# Associated Issues and/or People
- ADAPT-1199

### CODE REVIEW

**Comment by katrialesser** [comment]
@jenbreese this is good, but I'm also seeing another reason why it sometimes looks like a ton of space:
If the small super-header is empty, the empty span is adding empty space:
image

can you please add a line like .su-card span {
        &:empty {
          @apply hidden;
        }
        
        And that will also help with this problem. If you can add a test for this card without the small text superheader and check that both look okay, i think that is good.

**Comment by katrialesser** [comment]
A few notes:

- They did not request any changes to spacing above the icon or around the edges of the card, so I removed your adjustment @jenbreese on margin-top of the image.
- They only wanted spacing decreased below the icon. In addition to hiding the empty <span> that we discussed, i decreased the margin-bottom on the image by 1 increment in modular spacing; that was the main thing needed for this ticket, and then we noticed the empty span space was also interfering.
- Then I resolved conflicts with the branch

**Comment by katrialesser** [comment]
@jenbreese preview the change I made here: https://saauserguide-test.sites.stanford.edu/site-building-guide/saa-components-stanford-sites/cards/icon-cards

**Comment by jenbreese** [comment]
Looks good to me.

**Pull request merged**
