### PR TITLE
ADAPT-3244: Added webpack config for building React apps. 

### PR DESCRIPTION
**Pull request by nplowman**
# READY FOR REVIEW

# Summary
- Updates webpack config to support compiling React apps.
- Adds "hello world" React app on /search to demonstrate how we will add the Algolia Search widget into the search page. 

# Review By (Date)
- Next 1-2 days. Will need this work merged in order to proceed with other tickets related to Aloglia Search. 

# Criticality
- 5/10. Not urgent, but as mentioned this will need to be merged to proceed with other tickets. 

# Review Tasks

## Setup tasks and/or behavior to test

1. Enable the Victoria subtheme (set to this branch) on a Drupal site. 
2. Run 'npm run build' to re-compile theme assets. 
3. Validate that you see the build file for the hello-world app inside of [theme-folder]/dist/js/hello-world.js
4. In your browser, go to /search. You should see the "Hello World" text being rendered by the React app.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ADAPT-3244

# Other notes
- Unfortunately, building the React app does not work properly when running `npm run watch`.
- This is due to the "onStart" step for the FileManagerPlugin, which is deleting the entire dist folder. 
- The FIleManagerPlugin added a "runOnceInWatchMode" option in a more recent version than what is currently installed that would likely solve this issue. However, we would need to update other dependent packages first in order to do this, which could introduce other unexpected issues.

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
This all looks fine to me. 

@rebeccahongsf How do you want to handle maintenance and updates to this theme while Nathan is working on the search functionality? I suspect you will need to keep up with the core product and will likely release something between now and when the search functionality is completed. I would suggest that this work be merged into an integration branch until it is ready for prime time.

**Comment by rebeccahongsf** [comment]
@sherakama I agree — while the upcoming core updates seem to have little to no impact on sub themes, the search functionality should still be merged into an integration branch (I presume that is 2.x) until it is ready for release. In the meantime, any minor updates/fixes for core will continue to go into 1.x?

**Comment by nplowman** [comment]
@sherakama FYI - the "2.x" branch is a new branch we created specifically for keeping the Algolia search work separate. 
https://stanfordits.atlassian.net/browse/ADAPT-3216

**Comment by nplowman** [comment]
This work was built upon in ADAPT-3246 (port of the Algolia Search Page). This PR is no longer needed.

**Pull request closed without merging**
