### PR TITLE
D8CORE-6609 | @rebeccahongsf | add new class names

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- add new layout paragraph class names

# Review By (Date)
- asap

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to https://saauserguide-test.sites.stanford.edu/saa-site-building-guide/saa-components-stanford-sites/card-variants
2. Verify that the cards match [prod](https://saauserguide.sites.stanford.edu/site-building-guide/saa-components-stanford-sites/card-variants)
3. Review code

# Associated Issues and/or People
- D8CORE-6609

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Hi @rebeccahongsf 😄 I didn't pull this down locally so can't verify, but saw this huge line diff
Screenshot 2023-07-07 at 3 20 06 PM

Is this what you expected? It looks like it's from the dist/ css file 👀

**Comment by rebeccahongsf** [comment]
> Hi @rebeccahongsf 😄 I didn't pull this down locally so can't verify, but saw this huge line diff Screenshot 2023-07-07 at 3 20 06 PM
> 
> Is this what you expected? It looks like it's from the dist/ css file 👀

Oh yeah! That's the recompiled version of the css so that's expected 😅

**Review by yvonnetangsu — APPROVED** [review]
They do look the same to me. GTG 😄 !

**Comment by yvonnetangsu** [comment]
> > Hi @rebeccahongsf 😄 I didn't pull this down locally so can't verify, but saw this huge line diff Screenshot 2023-07-07 at 3 20 06 PM
> > Is this what you expected? It looks like it's from the dist/ css file 👀
> 
> Oh yeah! That's the recompiled version of the css so that's expected 😅

Oh I'm guess from non-minified to minified? 😂 (too many lines, can't view here on GitHub to see diff)

**Pull request merged**
